[metadata]
author = "Daniel Barrera and Edgar Alc√°ntara"
description = "Configuration for the Workshop"
version = "2025.06.21"

[settings]

# Choose the data provider
# Options: "yahoo_finance", "fmp"
provider = "yahoo_finance"


[api_keys]
# Only required if the selected provider needs an API key
fmp = "your_fmp_api_key_here"

# For the FRED Data, we need an API key
fred = 'your_fred_api_key_here'
