### TICKERS ###

[metadata]
author = "Daniel Barrera and Edgar Alc√°ntara"
description = "Tickers for the Workshop"
version = "2025.06.21"

#################################################
## Module 1 - Introduction to Financial Theory ##
#################################################

### Notebook 1.1 Introduction: Prices vs. Returns ###

[module."1.1".yahoo_finance]

tickers = ["AMZN", "NVDA"]

### Notebook 1.2 Introduction: Benchmark ###

[module."1.2".yahoo_finance]

tickers = ["^GSPC", "^DJI", "^NDX", "IWY"]

### Notebook 1.3 Portfolios: Risk Measurement ###

[module."1.3".yahoo_finance]

tickers = ['SPY', 'IWY', 'SPXL']


#################################
## Module 2 - Portfolio Theory ##
#################################

### Notebook 2.1 Correlation and Diversification ###

[module."2.1".yahoo_finance]

tickers = ['AMZN', 'MCD', 'WMT']

### Notebook 2.2 Markowitz Efficient Frontier ###

[module."2.2".yahoo_finance]

tickers = ['AAPL', 'AMZN', 'JPM', 'JNJ', 'XOM']

### Notebook 2.3 Capital Allocation Line ###

[module."2.3".yahoo_finance]

tickers = ['AAPL', 'AMZN', 'JPM', 'JNJ', 'XOM']

### Notebook 2.4 Rebalancing Portfolios ###

[module."2.4".yahoo_finance]

tickers = ['AAPL', 'AMZN', 'META', 'MSFT', 'NVDA']


#########################################
## Module 3 - Linear Regression Models ##
#########################################

### Notebook 3.2 Multiple Linear Regression ###

[module."3.2".yahoo_finance]

tickers = ['AAPL', '^GSPC', 'IWY', 'DX-Y.NYB', '^TNX']


############################################
## Module 4 - Capital Asset Pricing Model ##
############################################

### Notebook 4.4 Bet Against Beta ###

[module."4.4".yahoo_finance]

tickers = ['QCOM', 'T', 'CSCO', 'PFE', 'TSLA', 'ABT', 'AAPL', 'NKE', 'CVX', 'V']


###########################################
## Module 5 - Fama & French Factor Model ##
###########################################

### Notebook 5.1 Proving Size ###

[module."5.1".yahoo_finance]

tickers = [
    "VTV",  # LargeCap Value
    "VOE",  # MidCap Value
    "VBR",  # Small Cap Value
    "VV",   # LargeCap Blend
    "VO",   # MidCap Blend
    "VB",   # SmallCap Blend
    "VUG",  # LargeCap Growth
    "VOT",  # MidCap Blend
    "VBK"   # SmallCap Blend
]

### Notebook 5.2 Proving Value ###

[module."5.2".yahoo_finance]

tickers = [
    "VTV",  # LargeCap Value
    "VOE",  # MidCap Value
    "VBR",  # Small Cap Value
    "VV",   # LargeCap Blend
    "VO",   # MidCap Blend
    "VB",   # SmallCap Blend
    "VUG",  # LargeCap Growth
    "VOT",  # MidCap Blend
    "VBK"   # SmallCap Blend
]


#################################################
## Module 6 - Risk and Performance Attribution ##
#################################################

### Notebook 6.1 Brinson-Fachler Model ###

[module."6.1a".yahoo_finance]

tickers = ["AAPL", "JNJ", "JPM", "AMZN", "XOM", "UNP", "PLD"]

[module."6.1b".yahoo_finance]

tickers = ["XLK", "XLV", "XLF", "XLY", "XLE", "XLI", "XLRE"]

### Notebook 6.3 Menchero Risk Attribution ###

[module."6.3".yahoo_finance]

tickers = ['AAPL', 'AMZN', 'GOOG', 'META', 'MSFT', 'NVDA', 'TSLA']